import { describe, test, expect } from "bun:test";

describe("Phase 1.5 — Context Quality", () => {
  test.todo("SC-161: briefs assembled from prompts/*.md");
  test.todo("SC-162: prompts/*.md files exist with ≥10 lines");
  test.todo("SC-163: prompts/*.md change propagates without code edit");
  test.todo("SC-164: brief env URLs match rungate.json");
  test.todo("SC-165: Quinn brief frontmatter includes correct tools");
  test.todo("SC-166: brief env mismatch produces FAIL with fixCommand");
  test.todo("SC-167: AGENTS.md Specs table matches spec frontmatter");
  test.todo("SC-168: CODE-MAP.md under 3000 tokens");
  test.todo("SC-169: git hooks exist with executable permission");
  test.todo("SC-170: Tier 1 extra content produces WARN");
  test.todo("SC-173: ownership manifest declares all harness files");
  test.todo("SC-174: wraps ctxlint tokens rule");
  test.todo("SC-175: wraps agentsmd claude-length-warn");
  test.todo("SC-176: Hard Constraints >20 produces WARN");
  test.todo("SC-177: budget uses external tokenizer");
  test.todo("SC-178: ctxlint via Bun.spawnSync with prefix");
  test.todo("SC-179: agentsmd via Bun.spawnSync with prefix");
  test.todo("SC-180: agnix via Bun.spawnSync with prefix");
  test.todo("SC-181: RepoRails via Bun.spawnSync with prefix");
  test.todo("SC-182: agentsmd score in findings JSON");
  test.todo("SC-183: missing tools produce WARN");
  test.todo("SC-184: external fixCommand passthrough");
  test.todo("SC-185: no TODO/FIXME in instruction files");
  test.todo("SC-186: no contradictions via ccinspect");
  test.todo("SC-187: no secrets via ctxlint");
  test.todo("SC-188: dead hooks detected via ctxlint");
  test.todo("SC-189: no machine paths via agentsmd/agnix");
  test.todo("SC-190: instruction count under 150");
  test.todo("SC-191: briefs reference not duplicate Hard Constraints");
  test.todo("SC-192: sprawl-duplicate >70% flagged");
  test.todo("SC-193: AGENTS.md references findings file");
  test.todo("SC-194: inferability test on generated content");
  test.todo("SC-195: codebase grounding check");
  test.todo("SC-196: external checks run post-generation");
  test.todo("SC-197: regeneration on quality errors max 5");
  test.todo("SC-198: composite threshold configurable");
  test.todo("SC-199: scores written to scaffold-score.json");
  test.todo("SC-200: convergence logging");
  test.todo("SC-201: Hard Constraints human-reviewed only");
  test.todo("SC-202: rule provenance tracking");
  test.todo("SC-203: postinstall version stamp check");
  test.todo("SC-204: CI detects version change");
  test.todo("SC-230: ccinspect via Bun.spawnSync with prefix");
  test.todo("SC-231: positive framing preferred in generated content");
  test.todo("SC-232: second-occurrence rule for constraint promotion");
  test.todo("SC-233: cross-file contradiction detection");
  test.todo("SC-234: tool version tracking");
});
