// AUTO-GENERATED by scripts/sync-spec-tests.ts — do not edit manually
// Regenerate: bun scripts/sync-spec-tests.ts
// Source: specs/ (every spec with testable: true)
// Generated: 2026-10-09

import { test, expect, describe } from "bun:test";
import { readFileSync } from "fs";
import { join } from "path";
import { harnessRootFor } from "../lib/paths";

// Resolved at run time, not baked in: an absolute path written by whoever
// last ran the generator makes the file unrunnable anywhere else, CI
// included.
//
// Resolved from THIS file's own location, not from the implicit
// module-relative root (#190). These cases grade workflows/ship.js, and
// the implicit root honours HARNESS_ROOT — so a run with it set read a
// different checkout's ship.js than the one this file was generated
// from. A generated test grading a tree it does not belong to reports
// failures that exist in nobody's checkout.
const HR = harnessRootFor(join(import.meta.dir, ".."));
const SHIP_JS = readFileSync(join(HR, "workflows/ship.js"), "utf-8");
const PROVE_JS = readFileSync(join(HR, "workflows/prove.js"), "utf-8");

describe("auto-spec: ship.js claims from HARNESS-SKILL-CHAIN.md", () => {
  // Spec line 70: **Gate:** Template files with HIGH findings from agnix cannot ship. RepoRails findings are advisory 
  test("AUTO-GATE-1: Gate: Template files with HIGH findings from agnix cannot ship. RepoRails findings are", () => {
    expect(SHIP_JS.toLowerCase()).toContain("gate");
  });

  // Spec line 102: extracts four hardcoded claim shapes — `` `make x` ``, `**GATE:**`, ports, and
  test("AUTO-MAKE-1: Spec requires make x", () => {
    expect(SHIP_JS.toLowerCase()).toContain("x");
  });

  // Spec line 102: extracts four hardcoded claim shapes — `` `make x` ``, `**GATE:**`, ports, and
  test("AUTO-GATE-2: Gate: extracts four hardcoded claim shapes — `` `make x` ``, ``, ports, and", () => {
    expect(SHIP_JS.toLowerCase()).toContain("gate");
  });

  // Spec line 272: - **Container-only** → read project CLAUDE.md for container deploy command (e.g., `make rebuild`)
  test("AUTO-MAKE-1: Spec requires make rebuild", () => {
    expect(SHIP_JS.toLowerCase()).toContain("rebuild");
  });

  // Spec line 327: **Gate:** `bun test test/phase-0.test.ts` — 0 failures
  test("AUTO-GATE-1: Gate: `bun test test/phase-0.test.ts` — 0 failures", () => {
    expect(SHIP_JS.toLowerCase()).toContain("gate");
  });

  // Spec line 51: **Gate:** Issue exists with ACs. Before-state captured.
  test("AUTO-GATE-1: Gate: Issue exists with ACs. Before-state captured.", () => {
    expect(SHIP_JS.toLowerCase()).toContain("gate");
  });

  // Spec line 86: 3. Quinn validates locally (for UI tools: browser-based testing; for CLI tools: command execution an
  test("AUTO-QUINN-3: Quinn validates in SHIP", () => {
    expect(SHIP_JS.toLowerCase()).toContain("quinn");
  });

  // Spec line 96: 9. **GATE: Ship gate PASS. PR ready for review.**
  test("AUTO-GATE-5: Gate: 9.  Ship gate PASS. PR ready for review.", () => {
    expect(SHIP_JS.toLowerCase()).toContain("ship");
  });

});

describe("auto-spec: prove.js claims from HARNESS-SKILL-CHAIN.md", () => {
  // Spec line 118: 3. **Quinn validates in target environment**
  test("AUTO-QUINN-7: Quinn validates in PROVE", () => {
    expect(PROVE_JS.toLowerCase()).toContain("quinn");
  });

});
