// AUTO-GENERATED by scripts/sync-spec-tests.ts — do not edit manually
// Regenerate: bun scripts/sync-spec-tests.ts
// Source: PAI/specs/HARNESS-SKILL-CHAIN.md
// Generated: 2026-09-17

import { test, expect, describe } from "bun:test";
import { readFileSync } from "fs";
import { join } from "path";
import { harnessRoot } from "../lib/paths";

const HR = harnessRoot();
const SHIP_JS = readFileSync(join(HR, "workflows/ship.js"), "utf-8");
const PROVE_JS = readFileSync(join(HR, "workflows/prove.js"), "utf-8");

describe("auto-spec: ship.js claims from HARNESS-SKILL-CHAIN.md", () => {
  // Spec line 49: **Gate:** Issue exists with ACs. Before-state captured.
  test("AUTO-GATE-1: Gate: Issue exists with ACs. Before-state captured.", () => {
    expect(SHIP_JS.toLowerCase()).toContain("gate");
  });

  // Spec line 82: dev URLs come from project config, not hardcoded
  test("AUTO-CONFIG-3: API/UI URLs read from project config", () => {
    expect(SHIP_JS).toContain("projectConfig");
    expect(SHIP_JS).toContain("apiUrl");
    expect(SHIP_JS).toContain("uiUrl");
  });

  // Spec line 84: Quinn validates using config-driven URLs
  test("AUTO-QUINN-5: Quinn validates in SHIP", () => {
    expect(SHIP_JS.toLowerCase()).toContain("quinn");
  });

  // Spec line 90: container rebuild command comes from config
  test("AUTO-CONFIG-7: Container rebuild is config-driven", () => {
    expect(SHIP_JS).toContain("containerConfig");
    expect(SHIP_JS).toContain("rebuildCommand");
  });

  // Spec line 90: container port and hosts come from config
  test("AUTO-CONFIG-8: Container hosts/port from config", () => {
    expect(SHIP_JS).toContain("containerConfig");
    expect(SHIP_JS).toContain("containerPort");
    expect(SHIP_JS).toContain("containerHosts");
  });

  // Spec line 103: 13. **GATE: Ship gate PASS. PR ready for review.**
  test("AUTO-GATE-12: Gate: 13.  Ship gate PASS. PR ready for review.", () => {
    expect(SHIP_JS.toLowerCase()).toContain("ship");
  });

});

describe("auto-spec: prove.js claims from HARNESS-SKILL-CHAIN.md", () => {
  // Spec line 122: prove container startup is config-driven (was hardcoded make prove-up)
  test("AUTO-CONFIG-14: Prove container startup is config-driven", () => {
    expect(PROVE_JS).toContain("containerConfig");
    expect(PROVE_JS).toContain("proveUpCommand");
  });

  // Spec line 127: 3. **Quinn validates on prove container** (port 7776, prod data)
  test("AUTO-QUINN-15: Quinn validates in PROVE", () => {
    expect(PROVE_JS.toLowerCase()).toContain("quinn");
  });

});
