// AUTO-GENERATED by scripts/sync-spec-tests.ts — do not edit manually
// Regenerate: bun scripts/sync-spec-tests.ts
// Source: PAI/specs/HARNESS-SKILL-CHAIN.md
// Generated: 2026-09-17

import { test, expect, describe } from "bun:test";
import { readFileSync } from "fs";
import { join } from "path";
import { harnessRoot } from "../lib/paths";

const HR = harnessRoot();
const SHIP_JS = readFileSync(join(HR, "workflows/ship.js"), "utf-8");
const PROVE_JS = readFileSync(join(HR, "workflows/prove.js"), "utf-8");

describe("auto-spec: ship.js claims from HARNESS-SKILL-CHAIN.md", () => {
  // Spec line 49: **Gate:** Issue exists with ACs. Before-state captured.
  test("AUTO-GATE-1: Gate: Issue exists with ACs. Before-state captured.", () => {
    expect(SHIP_JS.toLowerCase()).toContain("gate");
  });

  // Spec line 82: 1. Marcus codes on local dev (make dev-all, :7778 API / :5173 UI)
  test("AUTO-PORT-3: Port 7778 referenced in SHIP context", () => {
    expect(SHIP_JS).toContain("7778");
  });

  // Spec line 84: 3. Quinn validates on local dev (:5173 UI, :7778 API)
  test("AUTO-PORT-4: Port 5173 referenced in SHIP context", () => {
    expect(SHIP_JS).toContain("5173");
  });

  // Spec line 84: 3. Quinn validates on local dev (:5173 UI, :7778 API)
  test("AUTO-QUINN-5: Quinn validates in SHIP", () => {
    expect(SHIP_JS.toLowerCase()).toContain("quinn");
  });

  // Spec line 90: 5. `make test-rebuild` → rebuilds container image from current code, starts on :7776 with seed data
  test("AUTO-MAKE-7: Spec requires make test-rebuild", () => {
    expect(SHIP_JS.toLowerCase()).toContain("test-rebuild");
  });

  // Spec line 90: 5. `make test-rebuild` → rebuilds container image from current code, starts on :7776 with seed data
  test("AUTO-PORT-8: Port 7776 referenced in SHIP context", () => {
    expect(SHIP_JS).toContain("7776");
  });

  // Spec line 103: 13. **GATE: Ship gate PASS. PR ready for review.**
  test("AUTO-GATE-12: Gate: 13.  Ship gate PASS. PR ready for review.", () => {
    expect(SHIP_JS.toLowerCase()).toContain("ship");
  });

});

describe("auto-spec: prove.js claims from HARNESS-SKILL-CHAIN.md", () => {
  // Spec line 122: 2. **Rebuild image + spin up isolated prove container** (`make prove-up`, port 7776)
  test("AUTO-MAKE-14: Spec requires make prove-up", () => {
    expect(PROVE_JS.toLowerCase()).toContain("prove-up");
  });

  // Spec line 127: 3. **Quinn validates on prove container** (port 7776, prod data)
  test("AUTO-QUINN-15: Quinn validates in PROVE", () => {
    expect(PROVE_JS.toLowerCase()).toContain("quinn");
  });

});
